### ISSUE TITLE
Default injector behavior should conform more to @Inject javadoc

### ISSUE THREAD

**Issue by ljacqu** [ljacqu/DependencyInjector#41]
- constructor injection and field injection can be mixed
- static fields may be injected

http://docs.oracle.com/javaee/6/api/javax/inject/Inject.html

**Comment by sgdc3** [comment]
> constructor injection and field injection can be mixed
👍

**Comment by ljacqu** [comment]
I find especially injection on static fields terrible; mixing constructor & field injection within the same class also to a lesser extent because it's more error-prone.
Maybe I extend the new injection method with restrictions regarding these two points, added as default. If someone wants the current one, just need to configure the injector appropriately.
