### ISSUE TITLE
Java 9 support

### ISSUE THREAD

**Issue by games647** [ljacqu/DependencyInjector#52]
Java 9 will be release in a few days and I noticed that the annotation `PostConstruct` is no longer available and therefore the application crashes with NoClassDefFoundError.

**Comment by sgdc3** [comment]
Should have been fixed

**Comment by games647** [comment]
So should I shade it into the jar?

**Comment by ljacqu** [comment]
Thank you guys. I could release a 0.4.1 or so if sgdc3's changes are needed soon, @games647

**Comment by sgdc3** [comment]
@ljacqu Yeah, would be better

**Comment by ljacqu** [comment]
hi @sgdc3 @games647, thanks again for the contribution. The fix is now available in a minor release, 0.4.1.
